### ISSUE TITLE
CCXT pro for nestjs

### ISSUE THREAD

**Issue by zizou86** [fasenderos/nestjs-ccxt#246]
Hi,

Thanks for this package, do you have a package for ccxtpro ?

Best Regards,

**Comment by fasenderos** [comment]
[CCXT Pro license](https://ccxt.pro/license)

> This CCXT Pro License **DOES NOT** grant a permission to publish, distribute, sublicense, and / or sell copies of the Software or substantial portions of the Software

In the [official CCXT Pro website](https://ccxt.pro/) they say that CCXT Pro will become a free part of CCXT in Q3 2022, when that happens I'll add it to this package.

**Comment by fasenderos** [comment]
@zizou86 CCXT Pro has been added to this package.
Best regards.
