### ISSUE TITLE
How can fetch the balance via apiKey and secretKey ?

### ISSUE THREAD

**Issue by zizou86** [fasenderos/nestjs-ccxt#255]
Hi Andrea,

Please, how can i fetch my balance using my apiKey and secretKey ?

Thanks

**Comment by fasenderos** [comment]
Hi zizou, to fetch your balance instantiate the ccxt client with your api key

```
const client = await this.ccxtService.getClient('binance', {
  apiKey: 'YOUR_API_KEY',
  secret: 'YOUR_SECRET',
});

const balance = await client.fetchBalance();
```
Hope that answers your question

**Comment by fasenderos** [comment]
Feel free to reopen this issue or just ask further questions here if any.
