### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by joshh71390** [fasenderos/nestjs-ccxt#392]
Hello, is it possible to contact you on say discord or skype or the likes... I have been building some smaller bots and am working on a much larger scale setup... -> I am only 1 year into coding but it is my lifes passion... i know this, im going 16 hours a day and only stopping out of necessity 

anyhow I would like to make some contributions to this project along the way both out of a sense of doing the right thing (opensource can only be as good as the material that is provided) and while I probably cant offer anything meaningful to ccxt it'self -> I think I could maybe add some stuff to this codebase that could benefit others (But stuff that is *below your paygrade* so it isnt the best use of your time...)

For starters I was thinking I could package up just a generic injection of the connector into a boilerplate nest app -> and instantiate some public apis -> and in just some generic ways that align with the ccxt examples directory.

then maybe throw a monorepo up-> then maybe show how it can be used -> with a front end -> stuff like that

I just want to make sure Im not wasting my time writing stuff that is breaking auth conventions / or trying to mount exchanges that are already connected / stuff like that

I have a general Understanding of everything I just need to air out a few concerns -> that you will be able to answer yes or no to , but theyre not the type of questions I will be able to ask in a nice detailed manner without some conversation because I lack the terminology of some of the more involved concepts, however I do understand them.

if you dont want to release your discord info I dont blame you I will give you mine so you can save yourself the potential spam -> feel free to not reply if you are too busy but I am looking to contribute to any types of projects that the work will be appreciated and also impactful and it seems like this is the one.

discord -> joshh#2273

**Comment by fasenderos** [comment]
Hi @joshh71390, thank you for your interest in this project.

> For starters I was thinking I could package up just a generic injection of the connector into a boilerplate nest app -> and instantiate some public apis -> and in just some generic ways that align with the ccxt examples directory.
> 
> then maybe throw a monorepo up-> then maybe show how it can be used -> with a front end -> stuff like that

So if I understand correctly, you want to create a backend/frontend with all the enpoints needed to connect and trade with an exchange. This is certainly an ambitious project, and you have to think a lot of things, but since this is your first year into coding I assure you that this is not a wasting time at all.

You will learn a lot of things even if you don't follow "best practices", and the open source community will help you improve your skills.

> anyhow I would like to make some contributions to this project along the way both out of a sense of doing the right thing (opensource can only be as good as the material that is provided) and while I probably cant offer anything meaningful to ccxt it'self -> I think I could maybe add some stuff to this codebase that could benefit others (But stuff that is below your paygrade so it isnt the best use of your time...)

Feel free to open any issue/PR, I'll be happy to hear and talk about your ideas, and any useful contribution will be added to this codebase.

> I have a general Understanding of everything I just need to air out a few concerns -> that you will be able to answer yes or no to , but theyre not the type of questions I will be able to ask in a nice detailed manner without some conversation because I lack the terminology of some of the more involved concepts, however I do understand them.

Don't worry about being wrong, even my english isn't perfect :)
If you write here all your questions me or other users will try to answer it and it will be helpful to the next people who come in here.

**Comment by joshh71390** [comment]
I dont mean everything, Im doing that type of project on my own right now I just mean some of the basic calls that can be made -> actually put to use instead of just having the snippet that goes into app module and service.

Nothing too crazy -> just kind of extending the documentation of it.

Also just a heads up i get some dependency issues when i try to run with the current version of nest so ill try to fix that, again ive never really messed with the dependencys of a package but i shall try =)
